Implement Pagination Backend
OWASP/Nest pull request #179
Opened 2024-12-14 17:50 UTC by harsh3dev

Resolves #56 

* This pull request introduces pagination to all API endpoints in the `backend/apps/owasp/api/search` 
* add page parameter
* include `nbPages` for getting total number of pages

2024-12-14 18:25 UTC, Rajgupta36 requested changes
hi @harsh3dev ,please set args page=1 by default and use the page-1 logic

2024-12-14 18:35 UTC, arkid15r requested changes
I agree `page=1` by default is more readable.

Could you apply the changes everywhere in the code?

Other than that looks good!

2024-12-14 18:35 UTC, arkid15r commented on backend/apps/owasp/api/search/chapter.py
> +def get_chapters(query, attributes=None, limit=25, meta=None, page=0):
```suggestion
def get_chapters(query, attributes=None, limit=25, meta=None, page=1):
```

2024-12-14 18:35 UTC, arkid15r commented on backend/apps/owasp/api/search/chapter.py
> +        "page": page,
```suggestion
        "page": page - 1,
```

2024-12-14 18:50 UTC, Rajgupta36 commented on backend/apps/owasp/api/search/chapter.py
> +        "page": page,
yes

2024-12-15 05:34 UTC, Rajgupta36 requested changes
Thanks 👍👍

2024-12-15 18:55 UTC, arkid15r approved these changes
I updated this a bit and merging into main
Thanks for another contribution @harsh3dev !

2024-12-15 18:59 UTC, merged