Feature : Pagination sharable comopnent
OWASP/Nest pull request #192
Opened 2024-12-16 21:31 UTC by Rajgupta36

Resolves #56  

## Description  
This PR includes the following changes:  
1. Implemented a reusable pagination component.  
2. Integrated the pagination component into the **Project** page.  
3. Integrated the pagination component into the **Committee** page.  
4. Adjusted Vue templates to ensure compatibility with the old project. However, pagination is not applied to the old project templates.  

## Checklist  
- [x] Pagination component is reusable.  
- [x] Pagination is functional on the **Project** page.  
- [x] Pagination is functional on the **Committee** page.  
- [x] Vue templates adjusted for compatibility with the old project.  

## Screenshots 
light mode
![image](https://github.com/user-attachments/assets/22a2edfa-053d-462b-af54-36ec1eae52d6)
 ---
 dark mode
  ![image](https://github.com/user-attachments/assets/42fedf2b-be66-467d-95da-f1fcc63d8a5d)
  ![image](https://github.com/user-attachments/assets/98e0493d-15e0-4a35-9b27-a068b772a950)

2024-12-18 04:09 UTC, arkid15r reviewed
Looking forward to reviewing another version of implementation as discussed in Slack 👍

2024-12-18 12:56 UTC, Rajgupta36 commented on frontend/src/components/Search.tsx
>    // eslint-disable-next-line no-unused-vars
cause it only use for state update

2024-12-18 12:56 UTC, Rajgupta36 commented on frontend/src/components/Search.tsx
> +  onSearch: (query: string) => void
eslint disable cause it is used for state updation only

2024-12-18 12:59 UTC, Rajgupta36 commented on frontend/src/components/Search.tsx
> +  onSearch: (query: string) => void
eslint disable cause it is used for state updation only

2024-12-18 13:00 UTC, Rajgupta36 commented on frontend/src/components/Pagination.tsx
> +  onPageChange: (page: number) => void
eslint disable cause it is used for state updation only

2024-12-18 13:02 UTC, Rajgupta36 commented on frontend/src/components/Search.tsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
we created this component once that' why i used empty array

2024-12-18 17:11 UTC, arkid15r requested changes
Great work!
It seems the very first load still 
<img width="585" alt="Screenshot 2024-12-18 at 9 10 41 AM" src="https://github.com/user-attachments/assets/9b895045-9aee-461b-b2a0-42e229c70581" />
makes 2 requests

I commented on some components but changes should be made on all of them:

2024-12-18 17:11 UTC, arkid15r commented on frontend/src/components/Loader.tsx
Could you use `LoadingSpinner` or `LoadingIndicator` as a name.

2024-12-18 17:11 UTC, arkid15r commented on frontend/package.json
I don't see package-lock.json changes though

2024-12-18 17:11 UTC, arkid15r commented on frontend/src/components/Loader.tsx
> +      className="relative h-16 w-16 animate-spin rounded-full border-4 border-[#98AFC7] dark:border-white"
Could you put it to the page center?

2024-12-18 17:11 UTC, arkid15r commented on frontend/src/components/Search.tsx
> +const SearchComponent: React.FC<SearchProps> = ({ onSearch }) => {
We need the `placeholder` as it's different for every page

2024-12-18 17:11 UTC, arkid15r commented on frontend/src/components/Search.tsx
> +            <X className="h-4 w-4 text-gray-400" />
The focus should still be on the search bar after user clicks on "X"

2024-12-18 17:11 UTC, arkid15r commented on frontend/src/lib/api.ts
> +  return data
```suggestion
  return await response.json()
```

2024-12-18 17:11 UTC, arkid15r commented on frontend/src/pages/Chapters.tsx
> +            <div className="text bg:text-white m-4 text-xl"> no Pages found </div>
```suggestion
            <div className="text bg:text-white m-4 text-xl">No chapters found</div>
```

2024-12-18 17:11 UTC, arkid15r commented on frontend/src/pages/Chapters.tsx
> +          {totalPages <= 0 && (
```suggestion
          {totalPages === 0 && (
```

2024-12-18 17:11 UTC, arkid15r commented on frontend/src/pages/Chapters.tsx
> +const ChaptersComponent = () => {
```suggestion
const ChaptersPage= () => {
```

2024-12-18 17:58 UTC, Rajgupta36 commented on frontend/package.json
added

2024-12-18 17:59 UTC, Rajgupta36 commented on frontend/src/components/Loader.tsx
> +      className="relative h-16 w-16 animate-spin rounded-full border-4 border-[#98AFC7] dark:border-white"
done

2024-12-18 17:59 UTC, Rajgupta36 commented on frontend/src/components/Search.tsx
> +const SearchComponent: React.FC<SearchProps> = ({ onSearch }) => {
done

2024-12-18 17:59 UTC, Rajgupta36 commented on frontend/src/components/Search.tsx
> +            <X className="h-4 w-4 text-gray-400" />
done

2024-12-18 17:59 UTC, Rajgupta36 commented on frontend/src/lib/api.ts
> +  return data
done

2024-12-18 18:02 UTC, Rajgupta36 commented
> Great work! It seems the very first load still <img alt="Screenshot 2024-12-18 at 9 10 41 AM" width="585" src="https://private-user-images.githubusercontent.com/2201626/397032843-9b895045-9aee-461b-b2a0-42e229c70581.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NDMyODUsIm5iZiI6MTczNDU0Mjk4NSwicGF0aCI6Ii8yMjAxNjI2LzM5NzAzMjg0My05Yjg5NTA0NS05YWVlLTQ2MWItYjJhMC00MmUyMjljNzA1ODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMThUMTcyOTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjE5NGM4Njk4NDJmMDA2NjA2MDM2YTM5YzJmNDJhOTFkZjM0ZTg1MGRiOTE1MDNlZDA1MzQxN2VlMjhkZDRlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.W-qvNU17QFaOOfLLkZfzO8BlHIl35beeBm1IBl7g3go"> makes 2 requests
> 
> I commented on some components but changes should be made on all of them:

it's cause of react strictmode

2024-12-19 20:01 UTC, arkid15r reviewed
LGTM

Just a small suggestion:

2024-12-19 20:01 UTC, arkid15r commented on frontend/src/lib/api.ts
> +  const response = await fetch(`${API_URL}/${endpoint}?q=${query}&page=${currentPage}`)
```js
fetch('https://example.com?' + new URLSearchParams({
    foo: 'value',
    bar: 2,
}).toString())
```

2024-12-19 20:06 UTC, Rajgupta36 commented on frontend/src/lib/api.ts
> +  const response = await fetch(`${API_URL}/${endpoint}?q=${query}&page=${currentPage}`)
it's already wrapped up in ` ` string

2024-12-19 20:08 UTC, arkid15r commented on frontend/src/lib/api.ts
> +  const response = await fetch(`${API_URL}/${endpoint}?q=${query}&page=${currentPage}`)
right, I suggest to create a mapping for better readability. a separate variable would be fine too.

2024-12-19 20:21 UTC, Rajgupta36 commented on frontend/src/lib/api.ts
> +  const response = await fetch(`${API_URL}/${endpoint}?q=${query}&page=${currentPage}`)
```
 const response = await fetch(
    `${API_URL}/${endpoint}?` +
      new URLSearchParams({
        q: query,
        page: currentPage.toString(),
      }).toString()
  )
```
updated

2024-12-19 20:27 UTC, arkid15r approved these changes
LGTM

This is major step, now we have search+pagination!

Thank you @Rajgupta36

2024-12-19 20:30 UTC, merged