Configure Dockerfile for staging environment
OWASP/Nest pull request #209
Opened 2024-12-19 12:16 UTC by harsh3dev

Resolves #191 

This pull request includes several changes to the `docker-compose-staging.yaml`, `frontend/Dockerfile.staging`, and `nginx/staging.conf` files to integrate and serve the frontend application in the staging environment. The most important changes are listed below:

Docker Compose configuration updates:
- [ ] Added a new `frontend` service configuration to the `docker-compose-staging.yaml` file. This includes setting up the container, build context, environment variables, and networking.
- [ ] Updated the `nginx` service configuration to use `staging.conf` instead of `nginx.conf` and added dependency on the `frontend` service.

2024-12-19 17:26 UTC, arkid15r requested changes
This needs some more work:

2024-12-19 17:26 UTC, arkid15r commented on frontend/Dockerfile.staging
> +COPY .env .env
This isn't right. In this case you'll have your secrets in the image which is available for downloading to anyone.

2024-12-19 17:26 UTC, arkid15r commented on docker-compose-staging.yaml
> +    env_file: ./frontend/.env
Use backend naming approach here too

2024-12-19 17:26 UTC, arkid15r commented on docker-compose-staging.yaml
> +    build:
We don't build on staging, we want to use a prebuilt image (see how it's done for backend)

2024-12-19 17:26 UTC, arkid15r commented on docker-compose-staging.yaml
> +      - "80"
Let's use 3000 for the FE for consistency.

2024-12-23 20:09 UTC, yashpandey06 commented
@arkid15r  can i work on this ?...the image will be served from docker-hub for frontend.

2024-12-24 22:05 UTC, arkid15r commented
Implemented in https://github.com/OWASP/Nest/commit/31626655b0cb5ea68ccbcc9f4bbb874496c6b83c

2024-12-24 22:05 UTC, closed without merging