Increased coverge for github management commands files
OWASP/Nest pull request #211
Opened 2024-12-19 19:34 UTC by Naveen-Pal

Resolves #182 

I have added the test file for the github/management/commands files. I have only tested the add_argument function. As handle function have some issue as it was connecting to database ( in this code "Issue.bulk_save(issues)"  ). I will again check that tomorrow or your suggestion may help. 
<br/>
In this pull request,
Total coverage have increased to 40%
<br/>
![image](https://github.com/user-attachments/assets/c79f750f-7ddf-444e-9750-52cdb9b854ef)
<br/>
![image](https://github.com/user-attachments/assets/aa215d6e-5214-4984-a1dc-f56f9c1b90f8)

2024-12-19 19:38 UTC, arkid15r commented
It's a good start and great improvement. In order to get the issue resolved we need 75%+ for these files.
I'll wait for the rest of test and then review it. Marking as draft for now.

2024-12-21 09:50 UTC, Naveen-Pal commented
I have updated the test to make their coverage 75%+
<br/>
![image](https://github.com/user-attachments/assets/e9b3facf-3e0d-47c2-8cbc-ab2ba1f921c0)
<br/>
![image](https://github.com/user-attachments/assets/714becd6-ce62-4186-acb2-355f00f8f0a8)

2024-12-21 20:16 UTC, arkid15r requested changes
Please look into these comments:

2024-12-21 20:16 UTC, arkid15r commented on backend/tests/github/management/commands/github_enrich_issues_tests.py
> +    type(mock_open_issues).without_summary = PropertyMock(return_value=mock_open_issues)
Is it possible to use other (more readable) syntax here?
If not please add a comment about `type(` usage

2024-12-21 20:16 UTC, arkid15r commented on backend/tests/github/management/commands/github_update_owasp_organization_tests.py
> +    ) as mock_repository_objects, mock.patch("builtins.print") as mock_print:
Could you format it in a more readable way using `with ():`

2024-12-21 20:16 UTC, arkid15r commented on backend/tests/github/management/commands/github_update_owasp_organization_tests.py
> +        if not repository_name:
Use `else` and move above the assertions.

2024-12-21 20:16 UTC, arkid15r commented on backend/tests/github/management/commands/github_update_project_related_repositories_tests.py
> +        if offset == 0:
Why 2 same ifs?

2024-12-22 17:12 UTC, Naveen-Pal commented
@arkid15r 
please check and suggest if any changes required.

2024-12-22 18:13 UTC, arkid15r approved these changes
It looks much better, thank you @Naveen-Pal!

I'll take it!

2024-12-22 18:17 UTC, merged