Increased coverage of owasp/models
OWASP/Nest pull request #263
Opened 2024-12-24 18:59 UTC by Naveen-Pal

I have increased the coverage for owasp/models/ more than 75%. 

 created: owasp/models/chapter_tests.py
 created: owasp/models/committee_tests.py
 created: owasp/models/common_tests.py
 created: owasp/models/event_tests.py
 modified: owasp/models/projects_tests.py

Below are the screenshots to see the actuall coverage percentage.
<br/>
![image](https://github.com/user-attachments/assets/125f0735-baa4-4fe7-86c9-81f716634c1d)
<br/>
![image](https://github.com/user-attachments/assets/11ddbf6c-dec3-45aa-a906-b39e991f463e)

2024-12-25 17:17 UTC, arkid15r requested changes
This is a good PR!
Could you make tests a part of a parent class instead of module level methods for Chapters, Committee, and Event?

Also:

2024-12-25 17:17 UTC, arkid15r commented on backend/tests/owasp/models/chapter_tests.py
> +    if not has_suggested_location:
Make `if has_suggested_location` condition check first.

2024-12-25 17:17 UTC, arkid15r commented on backend/tests/owasp/models/chapter_tests.py
> +    if not has_coordinates:
Make `if has_coordinates` condition check first.

2024-12-25 17:17 UTC, arkid15r commented on backend/tests/owasp/models/chapter_tests.py
> +            "tags": "tags",
thanks for the key sorting 👍

2024-12-25 17:17 UTC, arkid15r commented on backend/tests/owasp/models/committee_tests.py
> +    ("has_summary"),
It seems this param could be the summary value itself instead of `has_summary`

2024-12-25 17:17 UTC, arkid15r commented on backend/tests/owasp/models/committee_tests.py
> +    if not has_summary:
Check `if has_summary` first and group multiple ifs

2024-12-25 17:17 UTC, arkid15r commented on backend/tests/owasp/models/project_tests.py
> +        assert not project.is_active
Be consistent:
```suggestion
        assert project.is_active is False
```

2024-12-25 20:11 UTC, arkid15r commented on backend/tests/owasp/models/project_tests.py
> +        assert not project.is_active
Nevermind, `assert not ...` is fine.

2024-12-26 13:22 UTC, Naveen-Pal commented
@arkid15r Let me know if further improvement required.

2024-12-26 18:27 UTC, arkid15r approved these changes
Thanks for addressing the comments @Naveen-Pal 

I'm merging this

2024-12-26 18:32 UTC, merged