Add Markdown support
OWASP/Nest pull request #276
Opened 2024-12-26 13:44 UTC by harsh3dev

Resolves #251 
Resolves #86 

Added the markdown support using `react-markdown`, `remark` and `rehype` packages
Added mocks for these modules in `__mocks__`

https://github.com/user-attachments/assets/16c502f1-34db-4c48-9573-87c9a91fdc9c

![image](https://github.com/user-attachments/assets/279c317a-362d-447e-ba23-042c9a37d4d8)

2024-12-26 13:53 UTC, harsh3dev commented
https://github.com/user-attachments/assets/09fc2978-a1e7-467a-a651-5499c32225c7

2024-12-26 18:13 UTC, arkid15r requested changes
Looks good, great work!

Could you add some basic tests for the new functionality?

Thank you!

2024-12-26 18:13 UTC, arkid15r commented on frontend/src/index.css
> +}
Could you narrow it down to markdown scope only?

2024-12-26 18:13 UTC, arkid15r commented on frontend/src/components/Card.tsx
> +import ActionButton from './ActionButton'
Please use absolute imports

2024-12-27 18:55 UTC, arkid15r approved these changes
LGTM 👏

2024-12-27 18:59 UTC, merged