Implement Users page backend
OWASP/Nest pull request #289
Opened 2024-12-28 11:40 UTC by Yashgupta9330

Resolves #68
Made the backend of users page

2024-12-29 19:21 UTC, arkid15r requested changes
It seems a lot of my comments are based on your attempt to use User models for organization data. We have a separate model for that. 

Please address when you get a chance:

2024-12-29 19:21 UTC, arkid15r commented on backend/Makefile
> +	@CMD="poetry run python manage.py load_data" && $(MAKE) exec-backend-command
Why this change?

2024-12-29 19:21 UTC, arkid15r commented on backend/apps/github/api/user.py
We don't provide index data via API yet -- we use local DB data only. Please revert it.

2024-12-29 19:21 UTC, arkid15r commented on backend/apps/github/index/user.py
> +    """User index for OWASP GitHub organization members."""
```suggestion
    """User index."""
```

2024-12-29 19:21 UTC, arkid15r commented on backend/apps/github/migrations/0015_remove_user_is_hireable_remove_user_twitter_username_and_more.py
Could you take care of the migrations -- why you remove and then add fields back?

2024-12-29 19:21 UTC, arkid15r commented on backend/apps/github/models/user.py
> +    """Model representing a GitHub user or organization."""
We have a separate [model](https://github.com/OWASP/Nest/blob/main/backend/apps/github/models/organization.py) for GitHub organizations

2024-12-29 19:21 UTC, arkid15r commented on backend/apps/github/models/user.py
> +        blank=True,
Why `blank` here?

2024-12-29 19:21 UTC, arkid15r commented on backend/apps/github/models/user.py
> +            raise ValidationError(GITHUB_NODE_ID_REQUIRED)
Did you see cases when it was absent?

2024-12-29 19:21 UTC, arkid15r commented on backend/apps/github/models/user.py
> +            "public_repositories_count": "public_repos",
This is done in [GenericUserModel](https://github.com/OWASP/Nest/blob/4082718b8bf470557c38313595295724465254bc/backend/apps/github/models/common.py#L45)

2024-12-29 19:21 UTC, arkid15r commented on backend/data/copy.json.gz
Please revert this.

2024-12-29 19:21 UTC, arkid15r commented on backend/apps/github/models/user.py
> +    public_repositories_count = models.PositiveIntegerField(
It already exists -- https://github.com/OWASP/Nest/blob/4082718b8bf470557c38313595295724465254bc/backend/apps/github/models/common.py#L26

2024-12-29 19:21 UTC, arkid15r commented on backend/apps/github/models/user.py
> +    type = models.CharField(
As I mentioned -- users and orgs are separate entities.

2024-12-30 10:46 UTC, Yashgupta9330 commented on backend/apps/github/models/user.py
> +        blank=True,
it is because bio is optional

2024-12-31 00:33 UTC, arkid15r approved these changes

2024-12-31 00:37 UTC, merged