implement real time suggestion
OWASP/Nest pull request #292
Opened 2024-12-28 19:07 UTC by Rajgupta36

Resolves #148 

Implemented real-time suggestions using the autocomplete.js library provided by Algolia.
- [x] Created a `SearchBar` component
- [x] Added search logic
- [x] Set up a query suggestion index
- [ ] Implemented custom loading for the search bar
- [ ] Enhanced query handling for better suggestions

POW
----

https://github.com/user-attachments/assets/7946b043-2f74-4001-99d7-c689509ff1b5

2024-12-29 19:12 UTC, Rajgupta36 commented on frontend/src/components/AutoSuggestion.tsx
> +          indexName: indexName,
For now, use the hardcoded value `'issue_suggestions'` instead of the` indexName`

2024-12-29 19:15 UTC, Rajgupta36 commented on frontend/src/components/AutoSuggestion.tsx
> +      // eslint-disable-next-line react-hooks/exhaustive-deps
If i enable it . it renders component 5 times

2024-12-30 23:09 UTC, kasya commented
@Rajgupta36 Thank you for working on this! Could you please resolve existing conflicts before we review this one? Thanks!

2024-12-31 01:47 UTC, arkid15r requested changes
It seems we can create suggestions index [programmatically](https://www.algolia.com/doc/libraries/python/v4/methods/query-suggestions/create-config/?client=python).

2024-12-31 01:47 UTC, arkid15r commented on frontend/package.json
> +    "@algolia/autocomplete-theme-classic": "^1.17.8",
These are regular (non-dev) dependencies.

2024-12-31 01:47 UTC, arkid15r commented on frontend/src/components/Search.tsx
> +import Autocomplete from './AutoSuggestion'
Use absolute imports

2024-12-31 01:49 UTC, arkid15r reviewed
I also noticed multiple loading indicators upon data loading 🤷‍♂️

2024-12-31 01:52 UTC, arkid15r commented on frontend/src/components/AutoSuggestion.tsx
> +          openOnFocus: true,
```suggestion
          openOnFocus: false,
```

2024-12-31 09:16 UTC, Rajgupta36 commented on frontend/package.json
> +    "@algolia/autocomplete-theme-classic": "^1.17.8",
Thank you for pointing out

2024-12-31 09:22 UTC, Rajgupta36 commented
> I also noticed multiple loading indicators upon data loading 🤷‍♂️

yeah it's only when our component load first time . i am fixing it

2024-12-31 15:02 UTC, arkid15r reviewed
>It seems we can create suggestions index [programmatically](https://www.algolia.com/doc/libraries/python/v4/methods/query-suggestions/create-config/?client=python).

So what about the index settings, do we need to update them manually?

2024-12-31 15:02 UTC, arkid15r commented on frontend/jest.setup.ts
> +import React from 'react'
Does it need to be here? Can we group the imports?

2024-12-31 15:11 UTC, Rajgupta36 commented on frontend/jest.setup.ts
> +import React from 'react'
I think putting mock file in setup is good otherwise we need to mock it in all pages that used search bar

2024-12-31 15:13 UTC, Rajgupta36 commented
> > It seems we can create suggestions index [programmatically](https://www.algolia.com/doc/libraries/python/v4/methods/query-suggestions/create-config/?client=python).
> 
> So what about the index settings, do we need to update them manually?
We need new indexes for query suggestion . Maybe we can add facets value programmatically

2025-01-07 23:36 UTC, arkid15r requested changes

2025-01-07 23:36 UTC, arkid15r commented on backend/apps/common/management/commands/add_suggestion_index.py
> +                "indexName": f"{settings.ENVIRONMENT.lower()}_issues_suggestions",
Could you create a mapping for entity/faceted fields and use it in a loop to avoid code repetition?

2025-01-07 23:36 UTC, arkid15r commented on backend/Makefile
> +	@CMD="poetry run python manage.py add_suggestion_index" $(MAKE) exec-backend-command
```suggestion
	@CMD="poetry run python manage.py algolia_update_suggestions" $(MAKE) exec-backend-command
```

2025-01-07 23:36 UTC, arkid15r commented on backend/apps/common/management/commands/add_suggestion_index.py
> +            settings.ALGOLIA_WRITE_API_KEY, "eu"
```suggestion
            settings.ALGOLIA_WRITE_API_KEY,
```

2025-01-07 23:38 UTC, Rajgupta36 commented on backend/apps/common/management/commands/add_suggestion_index.py
> +            settings.ALGOLIA_WRITE_API_KEY, "eu"
region is mandatory either us or eu :-
```
# In an asynchronous context, you can use QuerySuggestionsClient instead, which exposes the exact same methods.
client = QuerySuggestionsClientSync(
    "ALGOLIA_APPLICATION_ID", "ALGOLIA_API_KEY", "ALGOLIA_APPLICATION_REGION"
)
```

2025-01-07 23:43 UTC, Rajgupta36 commented on backend/apps/common/management/commands/add_suggestion_index.py
> +                "indexName": f"{settings.ENVIRONMENT.lower()}_issues_suggestions",
thanks

2025-01-08 01:38 UTC, arkid15r requested changes

2025-01-08 01:38 UTC, arkid15r commented on frontend/__tests__/src/pages/Chapters.test.tsx
> -      expect(screen.queryByPlaceholderText('Search for OWASP chapters...')).not.toBeInTheDocument()
We still want it to load after the data is loaded.

2025-01-08 21:02 UTC, arkid15r reviewed
Please address these and let's merge it:

2025-01-08 21:02 UTC, arkid15r commented on backend/tests/common/management/commands/algolia_update_synonyms_tests.py
> +EXPECTED_CALL_COUNT = 5
You use it once, just inline it.
Also the scope is too broad, it's for one test only.

2025-01-08 21:02 UTC, arkid15r commented on frontend/__tests__/src/pages/Chapters.test.tsx
> +  test('renders  data, and pagination component concurrently after data is loaded', async () => {
```suggestion
  test('renders data and pagination component concurrently after data is loaded', async () => {
```

2025-01-08 21:02 UTC, arkid15r commented on frontend/src/components/Search.tsx
> +  indexName = 'issue_suggestions',
Do we need this value here?

2025-01-08 21:10 UTC, Rajgupta36 commented on frontend/src/components/Search.tsx
> +  indexName = 'issue_suggestions',
no

2025-01-08 21:53 UTC, arkid15r approved these changes
LGTM

2025-01-08 21:53 UTC, arkid15r commented on frontend/__tests__/src/pages/Chapters.test.tsx
> +  test('renders SearchBar, data and pagination component concurrently after data is loaded', async () => {
```suggestion
  test('renders SearchBar, data, and pagination component concurrently after data is loaded', async () => {
```

2025-01-08 22:01 UTC, arkid15r approved these changes

2025-01-08 22:04 UTC, merged