added gsoc year command
OWASP/Nest pull request #322
Opened 2024-12-31 18:24 UTC by Yashgupta9330

resolves https://github.com/OWASP/Nest/issues/259

2024-12-31 18:56 UTC, arkid15r requested changes
Please run pre-commit and add tests to your code as per [CONTRIBUTING.md](https://github.com/OWASP/Nest/blob/main/CONTRIBUTING.md#code-quality-checks)

2025-01-01 20:54 UTC, arkid15r requested changes
It works, let's make it look better and use DB for the queries:

2025-01-01 20:54 UTC, arkid15r commented on backend/apps/slack/commands/gsoc.py
> +    )
As I mentioned in the issue description we can use local DB data for getting the list. We don't need to query Algolia.

Move this logic to `Project::get_gsoc_projects(year)`

2025-01-01 20:54 UTC, arkid15r commented on backend/apps/slack/commands/gsoc.py
> +        try:
It seems you've removed "command is not supported" check.

2025-01-01 20:54 UTC, arkid15r commented on backend/apps/slack/commands/gsoc.py
> +            year = int(command_text)
Handle any input and exercise GSoC years logic when it's a number only.

2025-01-01 20:54 UTC, arkid15r commented on backend/apps/slack/commands/gsoc.py
> +            if year in VALID_YEARS:
Use a set for this kind of checks.

`VALID_YEARS = set(range(2020, 2025))`

2025-01-01 20:54 UTC, arkid15r commented on backend/apps/slack/commands/gsoc.py
> +VALID_YEARS = range(2020, 2025)
```suggestion
SUPPORTED_YEARS = range(2020, 2025)
```

2025-01-01 20:54 UTC, arkid15r commented on backend/apps/slack/commands/gsoc.py
> +                    blocks = [markdown(f"No projects found for GSOC {year}")]
This won't be a case. If it's a supported year there always be projects.

2025-01-01 20:54 UTC, arkid15r commented on backend/apps/slack/commands/gsoc.py
> +                        blocks.extend([markdown(f"<{hit['idx_url']}|{hit['idx_name']}>")])
Use a single markdown block, format project list w/ bullet points.

2025-01-05 19:06 UTC, arkid15r requested changes
I updated the command logic to handle the cases I mentioned.
Please update the tests and take care of unresolved comments

2025-01-05 19:06 UTC, arkid15r commented on backend/Makefile
> +	@docker build -f backend/Dockerfile.test backend -t nest-backend-test
Why this change?

2025-01-05 19:06 UTC, arkid15r commented on backend/apps/slack/commands/gsoc.py
> +                    f"• <{hit['idx_url']}|{hit['idx_name']}>" for hit in results["hits"]
I don't understand how you test/check the code. The database project entity doesn't have `idx_name` and `idx_url` fields -- they are from Algolia index.

2025-01-06 05:40 UTC, Yashgupta9330 commented on backend/Makefile
> +	@docker build -f backend/Dockerfile.test backend -t nest-backend-test
make test was not running before that

2025-01-06 10:09 UTC, Yashgupta9330 commented on backend/apps/slack/commands/gsoc.py
> +                    f"• <{hit['idx_url']}|{hit['idx_name']}>" for hit in results["hits"]
Actually, in my case, the data from the database was coming back empty

2025-01-06 17:56 UTC, arkid15r commented on backend/apps/slack/commands/gsoc.py
> +                    f"• <{hit['idx_url']}|{hit['idx_name']}>" for hit in results["hits"]
I suggest resolving that issue first. See [CONTRIBUTING.md](https://github.com/OWASP/Nest/blob/main/CONTRIBUTING.md#setting-up-the-project) sections 7/8.

2025-01-06 18:20 UTC, arkid15r commented on backend/Makefile
> +	@docker build -f backend/Dockerfile.test backend -t nest-backend-test
Try running it in WSL terminal

2025-01-07 04:09 UTC, kasya requested changes
Left some comments to address failing tests ⬇️

2025-01-07 04:09 UTC, kasya commented on backend/tests/slack/commands/gsoc_tests.py
> +            (True, "2019", "Usage: `/gsoc [year]`\nValid years: 2020-2024"),
I believe this should be for tests to pass. This doesn't match with current returned text for invalid year:
```suggestion
            (True, "2019", "Year 2019 is not supported. Supported years: 2020-2024"),
```

2025-01-07 04:09 UTC, kasya commented on backend/tests/slack/commands/gsoc_tests.py
> +                    assert "GSOC_GENERAL_INFORMATION_BLOCKS" in block_texts[0]
Also the patch didn't get applied properly here for a constant. If you print the value in the method - it's a regular constant and not the mock. I think it has to do with where the constant is imported. If you import it inside the method - test passes.

2025-01-07 04:09 UTC, kasya commented on backend/tests/slack/commands/gsoc_tests.py
> +            "apps.slack.commands.gsoc.get_gsoc_projects_by_year",
This should now be:
```suggestion
            "apps.owasp.models.project.Project.get_gsoc_projects",
```

2025-01-07 04:09 UTC, kasya commented on backend/tests/slack/commands/gsoc_tests.py
> +        }
And this should be changed to:
```suggestion
        mock_project = Mock()
        mock_project.nest_url = "https://owasp.org/www-project-bug-logging-tool/"
        mock_project.owasp_name = "Test Project"
        mock_projects = [mock_project]

```

2025-01-07 05:48 UTC, arkid15r approved these changes
LGTM 👍

2025-01-07 06:16 UTC, kasya approved these changes

2025-01-07 06:19 UTC, merged